// src/rocarray/quantized_stub.rs
// TEAM-502: Stub for ROCm quantized kernels
// 
// This is a temporary stub to allow compilation while we work on the actual
// HIP kernel implementation. The real kernels will be translated from
// candle-kernels/src/quantized.cu using hipify-clang.
//
// Status: STUB ONLY - NOT FUNCTIONAL
// TODO: Translate CUDA kernels to HIP (see .plan/TEAM_502_KERNEL_PARITY_VERIFICATION.md)

/// Stub HSACO binary for quantized kernels
/// 
/// This is an empty placeholder. The actual HSACO binary will be generated by:
/// 1. Translating quantized.cu to quantized.hip using hipify-clang
/// 2. Compiling quantized.hip to HSACO for target architectures (gfx1030, gfx1100, gfx90a)
/// 3. Embedding the HSACO binary here using include_bytes!()
/// 
/// Expected kernels (103 total):
/// - Dequantization kernels (F32 + F16): 22 kernels
/// - Quantization kernels: 1 kernel (quantize_q8_1)
/// - Fused dequant+matmul kernels: 10 kernels
/// - Batch matmul kernels (sizes 1-8): 60 kernels
/// - Full matmul kernels: 10 kernels
/// 
/// See: .plan/TEAM_502_KERNEL_PARITY_VERIFICATION.md for complete list
pub const QUANTIZED: &[u8] = &[];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quantized_stub_exists() {
        // Verify the stub constant exists
        assert_eq!(QUANTIZED.len(), 0, "Stub should be empty");
    }

    #[test]
    #[ignore = "Requires actual HSACO binary - not yet implemented"]
    fn quantized_kernels_loadable() {
        // This test will be enabled once we have real HSACO binaries
        // For now, it's ignored to allow compilation
        todo!("Implement after kernel translation (Phase 3.1-3.3)");
    }
}
